#include <iostream>
#include <string>
#include <fstream>
#include "egm.pb.h" // generated by Google protoc.exe

using namespace abb::egm;

static int portNumber = 6510;
static unsigned int sequenceNumber = 0;
const double rad_deg = 180 / 3.1415926;

struct cartesian_pose {
	double cart[3];
	double orient[3];
};

union pos {
	cartesian_pose cart_pose;
	double joints[6];
};

void CreateSensorMessage(EgmSensor* pSensorMessage, pos &pos, bool &joint_cmd);
void DisplayRobotMessage(EgmRobot *pRobotMessage);
